browser-history/browser-history

- .github/pull_request_template.md
- CONTRIBUTING.md
- docs/contributing.rst
Better, more complete contributing guidelines. Added basic PR template.
> Add contributing guidelines and PR template

- browser_history/generic.py
- browser_history/utils.py
Importing urlparse to strip the URL to find the domain name. A modification to #11 .
Fixes #10 
A modification to #11
> Fix #10 - Sorting domain-wise

- README.md
- browser_history/generic.py
- docs/quickstart.rst
- docs/requirements.txt
- tests/test_browsers.py
Renaming methods in browser_history.generic.Browser
Add class browser_history.generic.Outputs
Change documentation for the same.
Change Test script docs.test_browser
Fixes #13
> [CODE][DOC][TEST] Refactor & Rename Complete

- browser_history/cli.py
Made the browser argument case insensitive by using the `capitalize()` method.
Fixes #20 
> [FIX][CODE] made browser argument case insensitive

- browser_history/cli.py
Fixed issue #30 which is raised after PR #21 . Removal of TODO comment to indicate that the case-insensitivity feature has been fine-tuned. The unit tests and static code analysis are conducted with positive results.
Fixes # (issue) #30 
> fixed #30 - enhancement: removal of TODO

- browser_history/browsers.py
Added Opera browser support for Windows and Linux. 
Fixes #32 
[BROWSER] Opera support #32
Added Opera browser support
> Add opera support

- browser_history/browsers.py
Added `class OperaGX` in `browsers.py`
Fixes #33 
> [BROWSER] Add Opera GX support for Windows 

- browser_history/browsers.py
Added `windows_path` for Chromium in `browsers.py`
> Add Chromium support for Windows

- browser_history/browsers.py
Added support for `Brave` browser through creating a class `Brave` in `browsers.py`. Replaces previous weird PR (I still have no idea what went wrong).
Partially fixes #42
> [CODE] Add support for Brave Browser on Linux

- README.md
- browser_history/__init__.py
- browser_history/browsers.py
- browser_history/cli.py
- browser_history/generic.py
- browser_history/utils.py
- docs/quickstart.rst
- tests/test_browsers.py
I added the bookmarks feature for Firefox, and all Chrome based browsers, the relevant tests for them have also been updated.
Fixes #51 
> [FEATURE] Added Bookmarks support for Firefox and Chrome based browsers

- docs/API.rst
- docs/outputs.rst
- tests/test_generic.py
> [DOC] Document Outputs class

- README.md
- browser_history/__init__.py
- browser_history/browsers.py
- browser_history/cli.py
- browser_history/generic.py
- browser_history/utils.py
- docs/conf.py
- docs/quickstart.rst
- docs/requirements.txt
- tests/test_browsers.py
- tests/test_generic.py
This branch contains some major changes:
- Bookmarks feature: from #70 
- Renamed `Outputs.entries` to `Outputs.histories` (#70)
- Add features section in README
- Re-formatted using [black](https://github.com/psf/black)
- Some API changes
- Documentation update for these changes
> Bookmarks, some refactor and README update

- browser_history/__init__.py
- browser_history/browsers.py
- browser_history/cli.py
- browser_history/generic.py
- browser_history/utils.py
- docs/conf.py
- setup.py
- tests/context.py
- tests/test_browsers.py
- tests/test_generic.py
- tests/test_import.py
- tests/utils.py
I applied Black formatting, flake8 linting and also sorted import with isort (https://pypi.org/project/isort/).
I didn't want to touch logic so I just fix all findings with minor changes.
If you are ok with those changes, we can merge this and I will add those tools as pre-commit hook to automate everything.
> [FEATURE] Black, flake8, isort applied to codebase

- .flake8
- .github/pull_request_template.md
- .pre-commit-config.yaml
- README.md
- browser_history/__init__.py
- browser_history/cli.py
- browser_history/generic.py
- docs/contributing.rst
- tests/context.py
- tests/test_browsers.py
Here's the pre-commit hook with Black & flake8. I also added some builtin checks from pre-commit and some basic checks on .rst files.
Fixes #84
> Adding pre-commit hook

- .github/workflows/python-mypy.yml
Changed "name" field in mypy test workflow to remove ambiguity from other tests
#
This is my first ever PR. Trying to get one on the board!
> Changed "name" field in mypy test workflow

- .github/workflows/python-package.yml
Python version `3.9` added to the python-version list in YAML file
Fixes #111
> Fixes #111

- README.md
This PR is a documentation change WRT #120 .
Fixes #120 
> [DOC] fixed README to notify users who installed via pip of difference in docs

- browser_history/browsers.py
Added browser support for edge-dev on linux 
Fixes #80 
> [BROWSER] Added Edge support on linux

- docs/conf.py
Updated the copyright year from 2020 to 2020-2021 in the documentation .
Fixed issue #170 .
Minor update.
> Updated copyright year.

- browser_history/utils.py
- tests/test_utils.py
- tests/utils.py
Added tests for remaining untested lines in utils.py to increase test coverage.
Fixes #22 
No breaking changes, only some tests addition.
> [Tests] Increase test coverage for utils.py

- .github/workflows/python-package.yml
- browser_history/browsers.py
- browser_history/generic.py
> Fix failing CI

- browser_history/__init__.py
- docs/conf.py
A minor release. To be done after #260 is merged.
> [RELEASE] bump version to 0.3.3 🎉

- README.md
Cherry picked from the `release` branch.
> [DOC] update python version requirement in readme

- browser_history/__init__.py
- docs/conf.py
A feature release. See release notes (to be published after the release) for details.
> [RELEASE] bump version to 0.4.0 🎉

- browser_history/__init__.py
- docs/conf.py
Also merged the `release` branch
> Release v0.4.1 🎉 

- .github/workflows/python-docs.yml
- docs/requirements.txt
Closes:
- https://github.com/browser-history/browser-history/pull/219
- https://github.com/browser-history/browser-history/pull/233
- https://github.com/browser-history/browser-history/pull/253
- https://github.com/browser-history/browser-history/pull/257
- https://github.com/browser-history/browser-history/pull/258
> [DOC] Update all docs dependencies and remove unused ones
