browser-history/browser-history

browser_history/generic.py
The output list can be sorted asc/desc by setting the params to history() func.
The combined list of the entries can now be sorted either in ascending or descending order by specifying the choice as parameters to the history() function.
Fixes #3 
[CODE]
=> [CODE] Issue#3 Sort output

.pylintrc, browser_history/cli.py, docs/cli.rst, docs/conf.py, docs/index.rst, docs/quickstart.rst, docs/requirements.txt, setup.py
- This CLI has only two arguments - help and browser. Waiting for #15 to be merged before adding the 'all' option for browser choice.
- CLI is added to path in setup.py, allowing it to be called using `browser-history`.
- Usage: `browser-history -h`
- No documentation yet.
Fixes #5
=> [CLI] Add basic CLI 

README.md, browser_history/browsers.py, browser_history/utils.py, docs/contributing.rst, docs/index.rst, docs/quickstart.rst
1. Fix the grammar issue in index.rst
2. Change "Google Chrome Browser" to "Chromium Browser" in doc string.
3. `make html` produces a warning - Fix it by add a tabspace to docstring in utils.get_history
4. Demonstrate get_history in readme & quickstart
5. Add the line "Simultaneous update for Quickstart & README" to contributing.rst
Fixes #17
=> Documentation Modifications

browser_history/cli.py, browser_history/generic.py
Added method `formatted` which takes one argument `output_format` which is used to determine which formatter to use for the output history data. I also added class attributes `fields` and `formats` and private instance attribute `_format_map`, to make it easy for other contributors to add other output formats.
I also implemented the default format (CSV) by adding `to_csv` method to the `Outputs` class. This should provide a reference to other contributors implementing other formats.
Fixes #6
Fixes #34 
=> [ENHANCEMENT]Added foundation for exporting output to file

browser_history/browsers.py, tests/test_browsers.py
The section `NATURAL JOIN` in `Firefox.history_SQL` has been replaced with `INNER JOIN ON moz_historyvisits.place_id = moz_places.id` since `NATURAL JOIN` cannot implicitly handle the different field names `place_id` and `id`. Visit time will be derived from `moz_historyvisits.visit_date` and not `moz_places.last_visit_date` so as to capture all distinct visit times to the same URL. The test `test_firefox_linux` has also been modified to accommodate the new history entries that are returned due to this fix. 
Fixes #43
=> [CODE][FIX] Fix incomplete history while fetching from Firefox

browser_history/generic.py
The previous commit though worked for Linux and MAC-OS systems broke history fetching on Windows.I fixed it by using the rglob function from pathlib. I made sure to test it on Linux and Windows systems and it works fine. MAC-OS is yet to be tested . I would like a second confirmation as well for all the OS's so as to avoid such things in the future 
Fixes #58 
=> [BUG FIX] History failing on windows

.github/workflows/python-package.yml
Added Windows (latest) and Mac OS (latest) to the list of platforms to run the tests workflow on. This brings up the number of checks to 9. It should also prevent issues arising due to platform-specific changes.
Fixes #57
=> [FEATURE] add Windows and Mac OS to workflow

browser_history/generic.py
This fixes bug which resulted in `FileNotFoundError` when trying to fetch history from browsers supported on the current platform but not installed on it. This fix addresses that problem by checking if `generic.Browser.history_dir` is a path existing on the system. If this path is non-existent then the browser is probably not installed on that system and this information is logged and an empty profiles list is returned. This check is performed inside `generic.Browser.profiles` since every other functionality present and future will have to start by determining the profiles present.
Fixes #60 
=> [FIX] Fix error when fetching history from uninstalled browsers

browser_history/browsers.py, browser_history/generic.py
Mac OS path added for Brave,Edge and Opera browsers which enables support for Mac OS.
#42 
Fixes #1 
Fixes #32 
=> [Feature Added] Mac OS support added for Brave,Opera,Edge

browser_history/cli.py, browser_history/generic.py
Added save() function to Outputs, which makes saving the bookmarks or the history easier and which infers the output format from the file's extension.
Fixes #73 
=> save() function in Outputs

browser_history/browsers.py, tests/test_browsers.py
Updates Chrome `history_SQL` query to return only valid URL visits. Updated Edge test on windows which was affected by this issue.
Fixes #71
=> [FIX]Remove spurious history records

browser_history/generic.py, docs/conf.py, docs/requirements.txt
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- sort import based on isort
- use sphinx feature than list class member manually
- use type hint instead text for uniformed type description
- example code on some class function
- move comment about json_lines to to_json function
- comment out html_static_path to remove warning
- sphinx_autodoc_typehints
To view the result of this pr, #75  have to merged first
Fixes #63
=> [DOCS] Outputs class

browser_history/cli.py
Error prints are changd to use  utils.logger.error in cli.py
This refers issue #79
This change fixes #79, in that it replaces the use of the print statement with logger for error output in cli.py. The motiviation for this change is to display errors as such in the cli output - as logger outputs "ERROR: " with each error log.
Fixes #79 (issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ X] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [ X] I have performed a self-review of my own code (if applicable)
=> [CLI] Use logger for CLI errors (#79)

browser_history/cli.py
Currently, when a user enters an incorrect type through the `-t` flag, the following unfriendly error message is displayed:
```python
Traceback (most recent call last):
File "C:\Users\MANU\OneDrive\Projects\browser-history\runner.py", line 5, in <module>
main()
File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\cli.py", line 95, in main
assert (
AssertionError: Type should be one of all, history, bookmarks
```
This PR provides a better error message that is similar to that displayed when an invalid browser is entered hence providing a consistent user experience.
`ERROR: Type jgkhf is unavailable.Check --help for available types`
It also removes incorrect option `all` for type which was being suggested to the user. I believe we are yet to implement generation of all …
=> [CLI] Fix incorrect error message for invalid types

tests/utils.py
Close #91 by setting the home directory relative to the location of the `utils` test module, which is in a fixed location in the repo, rather than the current working directory where the test is run, which is independent of the repo location.
This means that running the `pytest` command alone in `browser-history/` or in `browser-history/tests/`, or indeed the `pytest <relative or absolute path to browser-history(/tests)>` command in any directory on the filesystem, results in a test suite pass (assuming the machine is in a timezone that is not one causing issue as per #90).
This PR requires no dependency changes.
- [n/a] I have made corresponding changes to the documentation (if applicable)
=> [TESTS] Remove test suite dependence on run directory

.github/workflows/python-package.yml, tests/test_browsers.py, tests/utils.py
Close #90 by making the `test_browser` history comparisons check for equivalence of datetimes in a way that is properly timezone aware due to use of the `dateutil.tz` module.
I wanted to avoid the need for any external module even in the test modules, given that the core codebase of `browser-history` has zero dependencies, but unfortunately after much investigation I found it was not possible to solve the issue without importing a truly timezone-aware library (`pytz` is another that will work) into the test in question. However, in Python 3.9 there is a built-in solution `zoneinfo` which can be used, so in future the new dependency can be removed with a tweak of the test to use that instead.
However, given the tests themselves require the `pytest` external library to run, I think it …
=> [TESTS] Timezone awareness for history datetime comparison

.github/workflows/python-docs.yml, .github/workflows/python-mypy.yml, browser_history/browsers.py, browser_history/generic.py, docs/functionality.rst
- add test using https://github.com/ammaraskar/sphinx-action
- change Browser class doc
- fix doc on Browsers and Outputs class
- include Browser class private member on documentation
- fix profile_dir_prefixes initiation, see https://stackoverflow.com/questions/9751554/list-as-a-member-of-a-python-class-why-is-its-contents-being-shared-across-all
Fixes #62
project can actually pass mypy test. i can add this to github worflow if requested
Sphinx-action workflow is based on their example and python-package.yml. It only work for linux environment
Based on documentation, some class field must be set for new browser 
but based on by given example it can be initiated with only one of the `path` field. 
There is also this SO question for some method to achieve this …
=> [DOC] Browser class

browser_history/__init__.py, browser_history/browsers.py, browser_history/cli.py, browser_history/generic.py
This PR adds a new abstract class `ChromiumBasedBrowser` in `generic.py`. This makes it easier for future contributors to add support for new chromium based browsers. As a consequence of this change, trying to access all browsers using `generic.Browser.__subclasses__()` doesn't work anymore. To solve this problem, I have added the `browser_history.get_browsers` function to recursively search for concrete browser classes starting from the abstract class `generic.Browser`
Fixes #104 
=> [REFACTOR] Add generic ChromiumBasedBrowser class

browser_history/generic.py
Works for the `dump.json` provided in #107  .
Added check for subsequent dictionaries, which was not noticed in #67  
Fixes #107  
=> [FIX] Fixed bug in bookmarks

browser_history/cli.py
`fetch_map` dictionary used in the `cli.py` is simplified to keep only the function name for "history" and "bookmarks" keywords since only one of them is used at a time.
Fixes #105
=> [CODE] Fixes #105

browser_history/cli.py, browser_history/generic.py, tests/test_cli.py
Fixes #65 by adding a test module to cover the command-line interface. **Still TODO in order to fix that Issue is the refactor of the CLI itself, but now I have a test it will be much simpler to gauge that the refactor has retained the previous behaviour.**
These new tests are, I believe, quite straightforward, with the only slight complication being that some browsers will not be available to a given machine running the tests, so tests running commands to grab the history from a given browser may need to be skipped. To skip those as appropriate on a browser-by-browser basis, I have created a parameterised test with the browser names as the parameters, so the result of running them (in verbose mode for illustration purposes, `pytest -v -v`)  is as follows:
```py …
```
=> [TESTS] Test module and refactor for CLI

.pylintrc, README.md, browser_history/__init__.py, browser_history/browsers.py, browser_history/cli.py, browser_history/generic.py, browser_history/utils.py, pytest.ini, tests/test_cli.py, tests/test_default_browser.py
This PR adds support for fetching history and bookmarks from default browsers.
|  | Linux | Mac | Windows |
|--|---------|-------|--------------|
|Chrome | ✔️     | 🔲  |✔️  |
|firefox | ✔️     |🔲   |✔️ |
|Chromium | ✔️   | 🔲  | ✔️   |
|Edge | ✔️    |🔲  | ✔️  |
|Brave | 🔲    | 🔲   |✔️  |
|Opera | ✔️    | 🔲   |✔️  |
|OperaGX | 🔲    | 🔲   | ✔️  |
|Safari| ➖    | 🔲   | ➖   |
|Vivaldi|  ✔️         |  🔲        |   🔲     |
Fixes #96
=> Add default browser support

browser_history/cli.py, browser_history/generic.py, browser_history/utils.py, tests/test_cli.py, tests/test_default_browser.py
This PR adds cli functionality allowing `--show-profiles` to display all available profiles for a browser and `-p/--profiles` to specify which profile to use when fetching history and bookmarks.
Along with these are the addition of 
1. `get_browser` method in `utils.py` which provides a cleaner way of getting the browser class from the strings provided in the 
CLI. 
2. `bookmark_path_profile` in `generic.py` which provides a way to get the path to a bookmark file in a given profile.
Fixes #74 
=> [FEATURE REQ] Add profile options in cli

.github/dependabot.yml
Added [dependabot](https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically) for documentation dependencies (sphinx, etc.).
=> Configure dependabot for docs dependencies

browser_history/generic.py, browser_history/utils.py, tests/test_cli.py
This commit makes get_browser return None for browsers not supported on current platform. This ensures you will not try to instantiate an unsupported browser and get an `AssertionError` or `NotImplementedError`. This useful in reducing unnecessary clutter in the CLI and other internal code.
Fixes #124
=> [CODE] Return None if requested browser is not supported on current platform

browser_history/generic.py
fixes #139
As discussed in the issue, this seems to fix problems when working with pipenv on macOS with pyenv-installed Python 3.8.9 and below.
To test:
1. Install pyenv and pipenv
2. create pipenv with Python 3.8.9: `pipenv install --python=3.8.9`
3. clone PR and run `pipenv install -e .` to install PR version
4. run `browser-history -b Firefox`
Fixes #139
- [y] I have read the [contribution guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) and followed it as far as possible. 
- [y ] I have performed a self-review of my own code (if applicable)
- [ depends] My changes generate no new warnings 
Pytest fails on windows and linux tests, but I guess that's expected on macOS
- [ y] I have enabled the pre-commit hook …
=> Fix Safari/Firefox bug in pipenv on macOS

docs/index.rst, docs/usage.rst
I noticed that there were no clear examples which showed everything that can be done with `browser-history`. Adding these to the quickstart would make it no longer be a "quick" start. So, I added a new section/chapter in the documentation that shows "what" you can do with `browser-history` along with "how" to do the thing that you need.
I got a little lazy with the Bookmarks section, since the code is pretty much the same except for the words being replaced.
Some examples for the CLI would also be useful (perhaps a future issue/PR).
=> [DOCS] add "Usage" section detailing all usecases with examples

browser_history/generic.py, browser_history/utils.py, tests/test_utils.py
- The error message when browser is unsupported on the current platform said `ERROR: <name> browser is unavailable. Check --help for available browsers`. The help section listed this as a valid browser name. This can cause confusion as the reason is that the browser is not supported on current platform.
- Added a new function `get_platform_name` in `utils` that returns a human readable name of the current platform.
- Added rudimentary tests for `get_platform` and `get_platform_name`
=> [CLI][TESTS] Fix error message when browser is unsupported and add tests for platform utils

.github/workflows/python-publish.yml
In this commit I have changed the release type from created to published in the pypi publish workflow.
Fixes #148 
=> [FIX] Changes the release type from created to published.

browser_history/cli.py
In this commit, I have added ASCII art in the cli.py, whenever `browser-history -h` will be used for run, It will show an ASCII art stating the BROWSER-HISTORY.
Fixes #162 
=> Adding ASCII art in CLI

.coveragerc, .flake8, .pylintrc, pytest.ini, setup.cfg, setup.py
Friday, September 24, 2021 - v0.3.1
- Support for a unified setup.cfg file which hosts all the configuration settings for the project.
- Updated the metadata within the config file to match the setup.py &  adopt a more declarative style of python project configuration.
- Deprecated `.coveragerc`, `.flake8`, `.pylintrc` and `pytest.ini` files.
=> [CODE] Use a setup.cfg instead of multiple config files

.github/workflows/python-docs.yml, .github/workflows/python-mypy.yml, .github/workflows/python-package.yml
Drop python 3.6 from CI runs. Add 3.11 instead.
As a side-effect, this also drops 3.8 and skips 3.10 to control the number of CI runs.
Note: this does NOT prevent browser-history from being installed on Python 3.6.
Fixes #240 
=> [CI] drop python 3.6 and add 3.10, 3.11

setup.py
Version check in setup.py was failing for version of python newer than 3.10 due to the manner in which the comparison was being done. This was redundant with the check that pip already performs, and the minimum version is already specified in setup.cfg.
Fixes #245
=> Remove failing Python version check from setup.py

browser_history/cli.py, browser_history/generic.py, tests/test_generic.py
When `Outputs.histories` (or `Outputs.bookmarks`) is being overwritten, the methods did not work correctly since they still pointed to the old variable. An example of this can be seen in [the docs for `sort_domain`](https://browser-history.readthedocs.io/en/stable/outputs.html#browser_history.generic.Outputs.sort_domain).
The PR fixes it and adds a test for it.
=> [FIX] make Outputs work even when .histories is overwritten

.github/workflows/python-package.yml
Tests are failing due to not being able to upload to codecov. Trying to see if this fixes it.
=> [CI] Update codecov uploader to v4

browser_history/__init__.py, browser_history/browsers.py, browser_history/generic.py, browser_history/utils.py, tests/test_browsers.py, tests/test_cli.py, tests/test_none_values.py
Some Safari entries have no title. If this is the case, and they have
the same URL and datetime, then we can't sort them. Python doesn't allow
comparing strings and None.
This uses the solution here:
<https://stackoverflow.com/questions/60695318/sort-a-list-of-tuples-with-none-values-in-python3>
It does not affect the output. If the datetime were to ever be None,
this could cause an issue, potentially.
The diff is large because of running black/fixing flake8 issues so the pre-commit hooks pass.
Fixes: https://github.com/browser-history/browser-history/issues/272
=> Fix Safari issue with no titles for history item

.readthedocs.yaml
Not even sure if this is a new format, but the docs build was failing on readthedocs:
```
Config validation error in build.os. Value build not found.
```
=> [CI] Update readthedocs config to the new format

.github/workflows/python-docs.yml, .github/workflows/python-mypy.yml, .github/workflows/python-package.yml, .github/workflows/python-publish.yml, .readthedocs.yaml
- Updated all checks to include python 3.12
- Updated all actions step versions (checkout, setup-python, etc.)
Support for python 3.7 is retained even though it's been EOL for many months now.
=> [CI] Support python 3.12 and clean up actions workflows

.github/workflows/python-mypy.yml, .github/workflows/python-package.yml, README.md, docs/contributing.rst
Python 3.7 went end-of-life 10 months ago: https://devguide.python.org/versions/#unsupported-versions
While this commmit does not forbid browser-history being installed with python 3.7 (which would be done in setup.cfg), it will be removed along with the update to using pyproject.toml in a separate PR.
See https://github.com/browser-history/browser-history/pull/279 for the WIP pyproject.toml PR and for some more reasons to drop 3.7.
=> [MISC] Drop support for Python 3.7

browser_history/cli.py
Piping output from the CLI in the terminal sometimes results in a `BrokenPipeError` which is currently unhandled. This PR adds handling of `BrokenPipeError` as well as `KeyboardInterrupt` which are the most common types of errors likely to occur during normal usage of the CLI.
Fixes #281
=> [CLI] Handle BrokenPipeError and KeyboardInterrupt (#281)
